spring:
  datasource:
    url: jdbc:mariadb://${RDS_DATABASE_ENDPOINT}:${RDS_PORT}/${RDS_DB_NAME}?serverTimezone=Asia/Seoul
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${RDS_DATABASE_USERNAME}
    password: ${RDS_DATABASE_PASSWORD}
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      dialect: org.hibernate.dialect.MariaDBDialect
      ddl-auto: none
    show-sql: true
    defer-datasource-initialization: true
cloud:
  aws:
    credentials:
      access-key: ${CLOUD_AWS_ACCESS_KEY}
      secret-key: ${CLOUD_AWS_SECRET_KEY}
    s3:
      bucket: ${S3_BUCKET_NAME}
      region: ap-northeast-2
    ses:
      mail-address: ${SES_MAIL_ADDRESS}
      region: ap-northeast-1

encryption:
  spec: ${ENCRYPTION_SPEC}
  secret: ${ENCRYPTION_SECRET}
  algorithm: ${ENCRYPTION_ALGORITHM}

jwt:
  secret: ${JWT_SECRET}

ableAutoComplete: true