spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:mariadb:10.6:///test
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      dialect: org.hibernate.dialect.MariaDBDialect
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
cloud:
  aws:
    credentials:
      access-key: test-accessKey
      secret-key: test-secretKey
    s3:
      bucket: test-bucket
      region: ap-northeast-2
    ses:
      mail-address: test-address
      region: ap-northeast-1
  sql:
    init:
      data-locations: classpath:db/testData.sql
      # (commented out) Sets the SQL file execution mode. When set to 'always', the SQL file is executed every time the application starts.
      # mode: always

exceed:
  url : http://loaclhost:8080
  deepLink :
    signUp: eatceed://checkemail
    updatePassword: eatceed://changepw


encryption:
  spec: AES
  secret: secretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecretsecret
  algorithm: AES

logging.level:
  org.hibernate.SQl: debug

jwt:
  secret: secretKeydlqslekdsecretKeydlqslekdsecretKeydlqslekdsecretKeydlqslekdsecretKeydlqslekdsecretKeydlqslekdse

ableAutoComplete: false

scheduler:
  nutrition:
    cache:
      update : 0 0 0 * * *

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: info
      springframework:
        test.context.cache: debug

