version: '3'
services:
  eatceed-mariadb:
    image: mariadb:10.6
    container_name: gaebaljip-mariadb
    expose:
      - "3306"
    volumes:
      - ./resources/gaebaljip-local-develop-environment/mariadb-conf:/etc/mysql/conf.d
      - ./resources/gaebaljip-local-develop-environment/mariadb-init:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
    networks:
      - gaebaljip-network

  eatceed-redis:
    image: redis:alpine
    container_name: gaebaljip-redis
    command: redis-server --port 6379
    expose:
      - "6379"
    networks:
      - gaebaljip-network

  eatceed-backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: gaebaljip-spring
    ports:
      - 8080:8080
    depends_on:
      - eatceed-mariadb
      - eatceed-redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://gaebaljip-mariadb:3306/gaebaljip?serverTimezone=Asia/Seoul
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - CLOUD_AWS_ACCESS_KEY=${CLOUD_AWS_ACCESS_KEY}
      - CLOUD_AWS_SECRET_KEY=${CLOUD_AWS_SECRET_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - SES_MAIL_ADDRESS=${SES_MAIL_ADDRESS}
      - ENCRYPTION_SPEC=${ENCRYPTION_SPEC}
      - ENCRYPTION_SECRET=${ENCRYPTION_SECRET}
      - ENCRYPTION_ALGORITHM=${ENCRYPTION_ALGORITHM}
      - SPRING_REDIS_HOST=gaebaljip-redis
      - SPRING_REDIS_PORT=6379
    networks:
      - gaebaljip-network
    restart:
      on-failure


networks:
  gaebaljip-network: