version: '3'
services:
  eatceed-redis:
    image: redis:alpine
    container_name: gaebaljip-redis
    command: redis-server --port 6379
    expose:
      - "6379"
    networks:
      - gaebaljip-network

  eatceed-backend:
    image: hwangdaesun/gaebaljip-prod:latest
    container_name: gaebaljip-spring
    ports:
      - 8080:8080
    depends_on:
      - eatceed-redis
    environment:
      - RDS_DATABASE_ENDPOINT=${RDS_DATABASE_ENDPOINT}
      - RDS_PORT=${RDS_PORT}
      - RDS_DB_NAME=${RDS_DB_NAME}
      - RDS_DATABASE_USERNAME=${RDS_DATABASE_USERNAME}
      - RDS_DATABASE_PASSWORD=${RDS_DATABASE_PASSWORD}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - CLOUD_AWS_ACCESS_KEY=${CLOUD_AWS_ACCESS_KEY}
      - CLOUD_AWS_SECRET_KEY=${CLOUD_AWS_SECRET_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - SES_MAIL_ADDRESS=${SES_MAIL_ADDRESS}
      - ENCRYPTION_SPEC=${ENCRYPTION_SPEC}
      - ENCRYPTION_SECRET=${ENCRYPTION_SECRET}
      - ENCRYPTION_ALGORITHM=${ENCRYPTION_ALGORITHM}
      - SPRING_REDIS_HOST=gaebaljip-redis
      - SPRING_REDIS_PORT=6379
      - SCHEDULER_NUTRITION_CACHE_UPDATE=${SCHEDULER_NUTRITION_CACHE_UPDATE}
    networks:
      - gaebaljip-network
    restart:  "always"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: "always"
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./resources/gaebaljip-prod-environment/grafana/provisioning/:/etc/grafana/provisioning/
    environment:
      - GF_SERVER_ROOT_URL=localhost:3000
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    depends_on:
      - prometheus
    networks:
      - gaebaljip-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: "always"
    ports:
      - "9090:9090"
    volumes:
      - ./resources/gaebaljip-prod-environment/prometheus/config:/etc/prometheus/
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - gaebaljip-network

volumes:
  grafana-data:
  prometheus-data:

networks:
  gaebaljip-network: